spring.application.name=misr_shoryan_elataa
server.port=9090
# Datasource (SQL Server)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=MisrShoryanElAtaa;encrypt=true;trustServerCertificate=true
spring.datasource.username=springBootUser
spring.datasource.password=StrongPassword@123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update

# # Fix for JSR-310 converters (Hibernate 6 compatibility)
# spring.data.jpa.repositories.enabled-context-converters=false

